[template]
src = "rundeck-config.properties.tmpl"
dest = "/home/rundeck/server/config/rundeck-config.properties"
keys = [
    "/rundeck/database/username",
    "/rundeck/database/password",
    "/rundeck/database/driver",
    "/rundeck/database/",
    "/rundeck/database/url",
    "/rundeck/server/address",
    "/rundeck/grails/url",
    "/rundeck/plugin"
]